### ISSUE TITLE
Openshift support

### ISSUE THREAD

**Issue by daniellelagziel** [litmuschaos/chaos-operator#114]
## Is this a BUG REPORT or FEATURE REQUEST?

 Choose one: BUG REPORT or FEATURE REQUEST
BUG REPORT 

**What happened**:
After applying cpu-hog experiment, we got security error:
AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: '/.ansible.
Running on openshift environment

**What you expected to happen**:
cpu-hog experiment

**How to reproduce it (as minimally and precisely as possible)**:
openshift v3.11.51
kubernetes v1.11.0+d4cacc0

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
@daniellelagziel , thank you for trying out litmus. We shall get back on this! cc: @uditgaurav

**Comment by uditgaurav** [comment]
@daniellelagziel can I know the ansible version you are using also do you have python openshift installed? As this experiment is using ansible k8s and k8s_fatcs module so it should satisfy the following criteria:
```
python >= 2.7
openshift >= 0.6
PyYAML >= 3.11
```
You can check python openshift using `pip freeze` and if it is not installed then install it using `pip install openshift`

**Comment by daniellelagziel** [comment]
I didn't have python openshift and PyYaml installed, I've installed it now, and the result of pip freeze are :
openshift==0.9.2
PyYAML==3.10

the python version is Python 2.7.16
I deleted the engine-nginx-runner and cpu-hog pods, but in recreation of cpu-hog pod, there is the same error : 
AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: '/.ansible'

**Comment by uditgaurav** [comment]
@daniellelagziel It seems that you don't have permissions to make .ansible in '/' please check once.

**Comment by daniellelagziel** [comment]
Is there any way to change the spec of cpu-hog ?
Right now the security context in the yaml of cpu-hog is -

securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1000190000

**Comment by ksatchit** [comment]
@daniellelagziel litmus has moved to golang for all chaos experiments - as the default, with considerable openshift users. Clsoing this issue, please feel free to re-open if you still face problems
