### ISSUE TITLE
Would it be good to merge `checkRunnerPodCompleted` & `checkRunnerPodForCompletion`

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/chaos-operator#163]
Would it be good to merge `checkRunnerPodCompleted` & `checkRunnerPodForCompletion`

_Originally posted by @ksatchit in https://github.com/litmuschaos/chaos-operator/pull/156/files_

**Comment by rakshitgondwal** [comment]
Is this open for grabs? @ksatchit @rahulchheda

**Comment by ispeakc0de** [comment]
It no longer exists. Resolved as part of refactoring
