### ISSUE TITLE
Refactor Codebase, for easier understanding

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/chaos-operator#175]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

- This is an umbrella issue to be tracked for `chaos-operator` bug fixes, and refactoring needed.
- Please comment on this issue with `litmuschaos/litmus`, or `litmuschaos/chaos-operator` issue to track them here.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/chaos-operator/issues/172

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/chaos-operator/issues/170

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/chaos-operator/issues/165

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/chaos-operator/issues/164

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/chaos-operator/issues/163

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/chaos-operator/issues/162

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/chaos-operator/issues/161

**Comment by rahulchheda** [comment]
Have raised a PR in reference to this: https://github.com/litmuschaos/chaos-operator/pull/176

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/litmus/issues/750

**Comment by neelanjan00** [comment]
Most of these issues have been refactored, let's track in separate issues if needed.
