### ISSUE TITLE
Can we validate that the GVR of `*unstructured.UnstructuredList` matches with `deploymentConfig` GVR, and then start to validate.

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/chaos-operator#201]
Can we validate that the GVR of `*unstructured.UnstructuredList` matches with `deploymentConfig` GVR, and then start to validate.

_Originally posted by @rahulchheda in https://github.com/litmuschaos/chaos-operator/pull/199_

**Comment by neelanjan00** [comment]
Closing this as this is no longer in use.
