### ISSUE TITLE
Add Directly invokable Namespace Chaos

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/chaos-operator#216]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by rahulchheda** [comment]
Just an issue to track update on: https://github.com/litmuschaos/litmus/issues/1523

**Comment by rahulchheda** [comment]
@ksatchit @chandankumar4 
We can start by creating a new CR in `v1alpha2` or a different name in`v1alpha1` package as well, add a separate reconcile function for it, and do namespace level chaos.
Do you guys have any ideas around it?

**Comment by ksatchit** [comment]
Closing this in lieu of https://github.com/litmuschaos/litmus/issues/1523 - a newer implementation of this will be tracked by a separate issue once prioritized
