### ISSUE TITLE
Different custom resources for each type of chaos 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/chaos-operator#225]
@ksatchit 
Just like user use kubernetes resource deployment,service ...e.t.c.
maybe user love more obvious statement,If I want to chaos pod that I must  to use the resource of ChaosPod , if i would like to chaos network that i should change the resource kind

_Originally posted by @jjmengze in https://github.com/litmuschaos/litmus/issues/1388#issuecomment-612606811_

**Comment by neelanjan00** [comment]
Descoping this as it is no longer relevant.
