### ISSUE TITLE
Automate creating PR weekly for chaos-operator into chaos-runner repo, to keep them consistent.

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/chaos-operator#277]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
The current consensus amongst the maintainers is to do this on a demand/need basis
