### ISSUE TITLE
Bump operator-sdk version for resolving go.mod directives in operator-sdk v0.15.2

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/chaos-operator#281]
BUG REPORT:

 ref: https://kubernetes.slack.com/archives/CNXNB0ZTN/p1602018149055400

 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by neelanjan00** [comment]
This is completed, closing the issue.
