### ISSUE TITLE
Allow the specification of a mount type on ChaosExperiment hostFileVolumes

### ISSUE THREAD

**Issue by chris-cmsoft** [litmuschaos/chaos-operator#323]
FEATURE REQUEST

**What happened**:

After updating OpenShift clusters, the mounting of the CRI for CRIO socket is failing.

```
MountVolume.SetUp failed for volume "cri-socket" : hostPath type check failed: /var/run/crio/crio.sock is not a file
```

New requirements are that the hostPath socket is mounted using type `Socket`.

When mounting the path using `Socket` it works correctly.

**What is the desired result**:

hostFileVolumes has a key `type` which can be used to change the type of the hostPath type on the underlying pod object.

**Comment by ksatchit** [comment]
Fixed since 1.13.0 (Refer issue tracked here: https://github.com/litmuschaos/litmus/issues/2410)
