### ISSUE TITLE
Feature Request: Add info about the resources under chaos

### ISSUE THREAD

**Issue by HristoDaskalovDev** [litmuschaos/chaos-operator#335]
## Feature Request: Add info about the resources under chaos

Feature request
**What happened**: ChaosEngine and ChaosResult do not contain information about the specific target of the chaos. 
For instance if I leave the 'appLabel' field empty, when the engine executes, how will I know on which pod, exactly did the chaos happen. Even if appLabel is filled, it would still be 
helpful to know the targets of the chaos. I can only see the targeted pod if i look at the logs of the helper pod.
**What you expected to happen**: I expect to be able to see the names of the pods, that the ChaosEngine is injecting chaos into, as well as the deployment they belong to. Either in the 
ChaosEngine or the ChaosResult.
**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**: A 'nice to have' would be to have a verdict (from ChaosResult) for each unique deployment. For example if 1 ChaosEngine does pod-kill on 3 pods, each from
a different deployment and the verdict is Fail, does this mean that one of them failed or all 3 ?

**Comment by ksatchit** [comment]
This is a great requirement!!

**Comment by neelanjan00** [comment]
We added this here: https://github.com/litmuschaos/litmus-go/pull/336, thanks for raising this issue! :)
