### ISSUE TITLE
Wrong default value of probe success percentage for experiments with `Awaited` status. Value is 100 instead of 0

### ISSUE THREAD

**Issue by ishangupta-ds** [litmuschaos/chaos-operator#346]
BUG REPORT 

**What happened**:

While running a chaos predefined workflow from litmus portal UI for sock-shop application, I deleted all the chaos engines and all workflows from the litmus namespace, resulting in the workflow failing, but somehow I got a resilience score as a non zero value, upon debugging it seems the experiment with awaited status had a probe success percentage of 100

**What you expected to happen**:

Ideally, as per the docs probe success percentage of awaited experiment result should have been 0 unless a concrete experiment verdict is available i.e either pass or fail.

**How to reproduce it (as minimally and precisely as possible)**:

Run a workflow from the litmus portal and delete the chaos engines and argo workflow created on the agent while it runs after the experiment job is created.

**Anything else we need to know?**:

API version and code reference: https://github.com/litmuschaos/litmus/blob/master/litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go

Here is the screenshot of the debugging.

<img width="872" alt="Screenshot 2021-03-16 at 1 06 49 PM" src="https://user-images.githubusercontent.com/50652677/111275993-d4c92f80-865c-11eb-99f6-8390202ad748.png">

**Comment by ishangupta-ds** [comment]
https://github.com/litmuschaos/litmus/pull/2558 This PR adds a check on the portal's frontend to filter the value but it will be helpful if it's handled at the infra level too.

**Comment by ishangupta-ds** [comment]
<img width="1536" alt="Screenshot 2021-03-30 at 12 56 59 PM" src="https://user-images.githubusercontent.com/50652677/112951017-8b96d680-9158-11eb-9da4-e8720d8e2c77.png">

**Comment by neelanjan00** [comment]
This has already been fixed, closing the issue. Thanks for raising the issue!
