### ISSUE TITLE
Does Litmus demo environment supports AKS ?

### ISSUE THREAD

**Issue by nitinkansal1984** [litmuschaos/chaos-operator#376]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
LitmusChaos as a framework works on AKS and has many community users on this platform.
