### ISSUE TITLE
Refactor the reconcile function of chaosengine controller 

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/chaos-operator#44]
The reconcile function today doesn't satisfy the BCH standards in terms of modularity & interfaces used. This issue will track refactor in this direction.

**Comment by ksatchit** [comment]
This is an umbrella issue for all the refactor activities around the reconcile function & bring it under BCH standards. Some of the PRs that have been merged as part of this effort are provided below: 

- #46 
- #36

**Comment by ksatchit** [comment]
The reconcile function has undergone several rounds of refactoring since. Further changes will be tracked under specific issue/enhancement requests.
