### ISSUE TITLE
Ignore the check from BCH of license text

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/chaos-operator#94]
I've selected for refactoring 15 lines of code which are duplicated in 3 file(s) ([1](https://github.com/litmuschaos/chaos-operator/blob/0f2c1944ab9fe31c8ce367e8e78258e02321457a/pkg/controller/resource/daemonset.go#L1-L22), [2](https://github.com/litmuschaos/chaos-operator/blob/0f2c1944ab9fe31c8ce367e8e78258e02321457a/pkg/controller/resource/deployment.go#L1-L22), [3](https://github.com/litmuschaos/chaos-operator/blob/0f2c1944ab9fe31c8ce367e8e78258e02321457a/pkg/controller/resource/statefulset.go#L1-L22)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

Issue generated by PR: https://github.com/litmuschaos/chaos-operator/pull/93

**Comment by chandankumar4** [comment]
Currently this is not supported by BCH

![Screenshot from 2019-11-21 00-17-52](https://user-images.githubusercontent.com/28861964/69268047-6903bd80-0bf4-11ea-99d7-e7d01b1eab30.png)

**Comment by ksatchit** [comment]
Closing this as an external dependency/issue.
